import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { NextTopLoader } from "@/widgets/next-top-loader";
import "./globals.css";
import { StoreProvider } from "./providers/store-provider";
import { themeConfig } from "@/shared/config/theme-config";
import { ConfigProvider } from "antd";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { MainLayout } from "./main-layout";

const geistSans = Montserrat({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable}`}>
        <NextTopLoader />

        <ConfigProvider theme={themeConfig}>
          <StoreProvider>
            <AntdRegistry>
              <MainLayout>{children}</MainLayout>
            </AntdRegistry>
          </StoreProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
