import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NextTopLoader } from "@/widgets/next-top-loader";
import "./globals.css";
import { StoreProvider } from "./providers/store-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StoreProvider>
          <NextTopLoader />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
