import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { NextTopLoader } from "@/widgets/next-top-loader";
import "./globals.css";
import { StoreProvider } from "./providers/store-provider";
import { MainLayout } from "./main-layout";
import {
  AntdConfigProvider,
  AntdRegistryProvider,
} from "./providers/antd-provider";

const geistSans = Montserrat({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable}`}>
        <NextTopLoader />

        <AntdConfigProvider>
          <StoreProvider>
            <AntdRegistryProvider>
              <MainLayout>{children}</MainLayout>
            </AntdRegistryProvider>
          </StoreProvider>
        </AntdConfigProvider>
      </body>
    </html>
  );
}
